import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
    title: "AeroTrans LTDA",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="flex justify-center mt-5"><Navbar/></div>
                {children}
            </body>
        </html>
    );
}
