import "./globals.css";
import Navbar2 from "@/app/components/Navbar";

export const metadata = {
    title: "AeroTrans LTDA",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="flex flex-col">
                    <Navbar2/>
                    <div>
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
